# OmniAuth Provider
provider: "twitter"
#provider: "facebook"
#provider: "github"

# Provider Page
provider_page: "https://twitter.com/"
#provider_page: "https://www.facebook.com/"
#provider_page: "https://github.com/"

# アプリケーション名
app_name: "Color Choice"

# プログラマTwitterID
programmer_twitter_id: "shu_0115"

# デザイナーTwitterID
designer_twitter_id: "DESIGNER_TWITTER_ID"
